name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Generate documentation (retrieve global tool)
      run: dotnet tool install xmldocmd -g
    - name: Generate documentation (generate)
      run: xmldocmd ${{ github.repository }} ${{ github.repository }}\bin\Debug\netcoreapp3.0\${{ github.repository }}.dll docs --source https://github.com/wokhansoft/${{ github.repository }}
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.1.0
      with:
        add: docs
        message: Automated documentation update
        ref: docs/test 
